INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (1,"Curabitur egestas","Cum sociis natoque penatibus et magnis dis");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (2,"mauris elit,","Quisque porttitor eros nec tellus.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (3,"odio. Phasellus","adipiscing, enim mi tempor lorem, eget mollis lectus pede et");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (4,"enim. Nunc","Maecenas ornare egestas");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (5,"rutrum.","ligula eu enim. Etiam imperdiet");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (6,"lorem,","aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (7,"Vestibulum","natoque penatibus et");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (8,"pharetra ut,","Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (9,"Donec nibh.","ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (10,"quis","malesuada vel, convallis in, cursus");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (11,"natoque penatibus","urna justo faucibus lectus, a sollicitudin orci sem eget");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (12,"Curabitur","metus eu erat semper rutrum.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (13,"tellus eu","eleifend, nunc risus varius orci, in consequat");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (14,"vitae, erat.","arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (15,"mollis. Integer","Nulla eu neque pellentesque massa");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (16,"nisl sem,","nunc. In at");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (17,"ornare, facilisis","commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (18,"Mauris","Donec elementum, lorem ut aliquam");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (19,"volutpat ornare,","sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (20,"Mauris","non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (21,"nisl","Mauris non dui nec urna suscipit");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (22,"eu sem.","In mi pede, nonummy ut, molestie in, tempus");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (23,"elit. Curabitur","Phasellus vitae mauris sit amet lorem semper");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (24,"mauris ipsum","sapien. Aenean massa. Integer vitae nibh. Donec");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (25,"enim. Etiam","Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (26,"justo sit","amet, consectetuer adipiscing");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (27,"ultricies","Fusce mi lorem, vehicula et,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (28,"mus. Donec","non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (29,"libero. Morbi","Nunc commodo auctor velit. Aliquam");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (30,"quis","non justo. Proin non massa");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (31,"aliquet magna","lectus justo eu arcu. Morbi sit amet massa. Quisque");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (32,"Duis","ullamcorper magna. Sed eu");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (33,"Aenean","lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (34,"eu","at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (35,"eu, euismod","libero. Integer in magna. Phasellus dolor elit,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (36,"Aenean eget","pede. Nunc");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (37,"fringilla mi","bibendum. Donec felis orci, adipiscing non,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (38,"turpis","elementum purus,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (39,"In","semper erat, in consectetuer ipsum nunc id enim.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (40,"nulla.","vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (41,"posuere at,","Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (42,"imperdiet","dui lectus rutrum");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (43,"risus","Nulla eget metus");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (44,"neque.","Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (45,"libero.","feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (46,"nunc sed","ipsum porta");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (47,"et malesuada","felis. Nulla tempor");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (48,"Proin","Maecenas iaculis aliquet diam. Sed diam");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (49,"est ac","vitae mauris sit amet lorem semper auctor. Mauris vel turpis.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (50,"eget","eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (51,"pharetra, felis","Phasellus dapibus quam quis");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (52,"sagittis felis.","nulla ante, iaculis nec, eleifend non,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (53,"Vestibulum","vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (54,"odio.","orci lacus vestibulum lorem, sit amet ultricies sem magna");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (55,"eros. Proin","ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (56,"pellentesque,","lobortis, nisi nibh lacinia orci,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (57,"lacus","natoque penatibus et magnis dis");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (58,"aliquet","ipsum primis in faucibus");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (59,"fermentum convallis","Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (60,"semper tellus","Sed dictum. Proin eget");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (61,"ridiculus mus.","Nullam scelerisque neque sed sem egestas blandit. Nam nulla");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (62,"Vestibulum ante","lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (63,"mollis. Integer","Etiam vestibulum massa rutrum");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (64,"auctor","pede blandit");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (65,"Proin","varius ultrices, mauris ipsum porta elit, a feugiat");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (66,"non sapien","ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (67,"Cras vehicula","eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (68,"commodo","Maecenas iaculis aliquet diam. Sed diam");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (69,"feugiat","fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (70,"augue","ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (71,"Nunc","Nunc ut erat. Sed nunc");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (72,"diam","lectus pede et risus. Quisque libero lacus,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (73,"Nunc commodo","Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (74,"aliquet lobortis,","leo. Cras vehicula aliquet libero. Integer in");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (75,"eu, eleifend","pede, nonummy ut,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (76,"commodo ipsum.","ut erat. Sed nunc est, mollis non, cursus non, egestas");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (77,"massa. Suspendisse","id, ante. Nunc mauris sapien, cursus");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (78,"pede","accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (79,"ligula","Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (80,"Nam","magna. Praesent interdum ligula eu enim.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (81,"Aenean","vehicula et, rutrum eu, ultrices sit");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (82,"risus. Morbi","risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (83,"tortor. Nunc","elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (84,"sapien","lobortis. Class");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (85,"Nullam velit","adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (86,"ultrices.","risus. Nulla eget metus eu erat semper");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (87,"mollis","tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (88,"sem, consequat","in felis. Nulla tempor augue ac");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (89,"tempus","cursus in, hendrerit consectetuer,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (90,"ligula.","nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (91,"Suspendisse","orci, consectetuer euismod est arcu ac orci. Ut semper pretium");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (92,"euismod ac,","eget metus eu erat semper rutrum. Fusce");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (93,"ornare","tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (94,"ultrices","natoque penatibus");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (95,"vitae, orci.","massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (96,"adipiscing","sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (97,"aliquet","sit amet massa. Quisque porttitor eros");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (98,"neque","cursus non,");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (99,"Nam tempor","Ut tincidunt vehicula risus.");
INSERT INTO `CategoryProduct` (`id`,`name`,`description`) VALUES (100,"lorem,","quam, elementum at, egestas");
