INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (1,"pede.","lacus. Aliquam rutrum lorem ac");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (2,"nibh","lacus. Mauris non dui nec");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (3,"magna.","fringilla cursus purus. Nullam scelerisque neque sed");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (4,"quam,","auctor, velit eget laoreet posuere, enim nisl elementum purus, accumsan");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (5,"et","purus mauris a nunc. In at pede. Cras vulputate");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (6,"tincidunt","tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (7,"ornare.","egestas. Fusce aliquet magna a neque. Nullam ut nisi");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (8,"adipiscing","eget, venenatis a, magna. Lorem ipsum dolor sit");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (9,"accumsan","vitae dolor. Donec fringilla. Donec feugiat");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (10,"enim.","velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (11,"eu","Duis mi enim, condimentum eget, volutpat ornare, facilisis");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (12,"sollicitudin","odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (13,"Morbi","ac metus vitae velit egestas lacinia. Sed congue, elit");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (14,"nulla","nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (15,"vitae","at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (16,"ullamcorper,","luctus. Curabitur egestas nunc sed libero. Proin sed turpis");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (17,"magna,","egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (18,"in","nec urna et arcu imperdiet ullamcorper. Duis at lacus.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (19,"aliquet,","commodo tincidunt nibh. Phasellus nulla. Integer");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (20,"nec","Duis gravida. Praesent eu nulla at sem molestie");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (21,"Integer","non, luctus sit amet, faucibus ut, nulla. Cras");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (22,"est,","a purus. Duis elementum, dui quis accumsan");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (23,"risus.","Sed pharetra, felis eget varius ultrices, mauris");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (24,"Curabitur","Quisque purus sapien, gravida non,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (25,"erat.","luctus, ipsum leo elementum sem, vitae aliquam");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (26,"est,","augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (27,"urna.","arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (28,"semper","mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (29,"sed","ut mi. Duis risus odio, auctor");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (30,"fermentum","a, arcu. Sed et libero. Proin");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (31,"vulputate","Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (32,"rutrum","non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (33,"Nunc","Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (34,"eu","purus. Maecenas libero est, congue");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (35,"In","nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (36,"parturient","Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (37,"egestas","Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (38,"nisi.","sagittis augue, eu tempor erat neque non quam. Pellentesque habitant");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (39,"tristique","sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (40,"eleifend","ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (41,"orci","turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (42,"enim","hendrerit a, arcu. Sed et libero.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (43,"at","blandit. Nam nulla magna, malesuada vel,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (44,"Phasellus","semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (45,"imperdiet","tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (46,"vel","eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (47,"adipiscing","Maecenas mi felis, adipiscing fringilla, porttitor");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (48,"eu","tristique neque venenatis lacus. Etiam bibendum fermentum metus.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (49,"Duis","orci. Phasellus dapibus quam quis diam. Pellentesque habitant");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (50,"aliquet","lorem, eget mollis lectus pede et risus.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (51,"vel","Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (52,"lectus","aliquam iaculis, lacus pede sagittis augue, eu tempor");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (53,"Maecenas","risus varius orci, in consequat enim diam vel arcu.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (54,"lacinia","mus. Donec dignissim magna a tortor. Nunc commodo auctor");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (55,"Nullam","Vestibulum ante ipsum primis in faucibus");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (56,"Proin","commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (57,"Nunc","pede et risus. Quisque libero lacus, varius et, euismod et,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (58,"eget","libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (59,"tincidunt","odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (60,"ornare,","tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (61,"In","amet, faucibus ut, nulla. Cras");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (62,"in","pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (63,"sit","nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (64,"mi","Vestibulum ut eros non enim commodo hendrerit. Donec");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (65,"mi","et ultrices posuere cubilia Curae; Donec");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (66,"gravida","dui, in sodales elit erat vitae risus. Duis");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (67,"Mauris","nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (68,"nascetur","Quisque nonummy ipsum non arcu. Vivamus sit amet");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (69,"egestas","mi tempor lorem, eget mollis lectus");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (70,"massa","Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (71,"purus.","velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (72,"mauris","faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (73,"felis","amet diam eu dolor egestas");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (74,"non,","lectus sit amet luctus vulputate, nisi sem semper erat,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (75,"consequat","mus. Proin vel arcu eu odio tristique");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (76,"mattis","aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (77,"pretium","Nunc pulvinar arcu et pede. Nunc sed orci lobortis");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (78,"netus","cubilia Curae; Donec tincidunt. Donec vitae erat");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (79,"rutrum","dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (80,"lorem","ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (81,"Fusce","feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (82,"metus","Mauris eu turpis. Nulla aliquet. Proin");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (83,"erat,","ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (84,"bibendum","Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (85,"blandit","sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (86,"ante","velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (87,"massa.","ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (88,"tincidunt.","at, velit. Pellentesque ultricies dignissim");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (89,"auctor,","Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (90,"cubilia","nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (91,"lobortis","auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis.");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (92,"nibh.","Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (93,"posuere","nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (94,"pharetra","vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (95,"ipsum","Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (96,"Nulla","scelerisque neque sed sem egestas blandit. Nam");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (97,"Nunc","magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (98,"sit","at, libero. Morbi accumsan laoreet ipsum. Curabitur");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (99,"arcu.","penatibus et magnis dis parturient montes,");
INSERT INTO `OrderStatusId` (`id`,`name`,`description`) VALUES (100,"magna","orci luctus et ultrices posuere");
